Raise correct exception to indicate ‘not implemented’ (#51)
The code incorrectly tries to raise `NotImplemented` in a few places,
which is a special value that is used as a return value in some
scenarios. It is not an exception type and cannot be raised:

    >>> raise NotImplemented
    ...
    TypeError: exceptions must derive from BaseException

The fix is to raise `NotImplementedError` instead.